# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
  service_account:
    description: 'Base64 encoded service account JSON from GCP IAM service account'
    required: true
  name:  # id of input
    description: 'PROJECT_ID/REPONAME:TAG format'
    required: true
  registry:  # id of input
    description: 'GCR registry host, It could be gcr.io/us.gcr.io/eu.gcr.io/asia.gcr.io'
    required: true
    default: 'gcr.io'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.service_account }}
    - ${{ inputs.name}}
    - ${{ inputs.registry}}