# action.yml
name: 'docker-build-push-gcr-update-gke-deployment-action'
description: 'Build docker image, push to GCR and update GKE deployment in defined namespace'
inputs:
  service_account:
    description: 'Base64 encoded service account JSON from GCP IAM service account'
    required: true
  zone: 
    description: 'Cluster Zone'
    required: true
  project_id:
    description: 'project id from GCP'
    required: true
  registry: 
    description: 'GCR registry host, It could be gcr.io/us.gcr.io/eu.gcr.io/asia.gcr.io'
    required: true
    default: 'gcr.io'
  image_name:  
    description: 'name of the image'
    required: true  
  cluster:  
    description: 'Name of GKE cluster'
    required: true
  namespace:  
    description: 'namespace of the deployment'
    required: true
    default: 'default'
  deployment:  
    description: 'name of the deployment which needs to be update'
    required: true
  container:  
    description: 'name of container whose image needs to be updated'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service_account }}
    - ${{ inputs.image_name}}
    - ${{ inputs.registry}}
    - ${{ inputs.cluster}}
    - ${{ inputs.zone}}
    - ${{ inputs.project_id}}
    - ${{ inputs.namespace}}
    - ${{ inputs.deployment}}
    - ${{ inputs.container}}
