on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build and push image to GCR and then update GKE deployment with that image.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image Push to GCR and Update GKE deployment
        uses: ./ 
        id: hello
        with:
          service_account: ${{ secrets.GCLOUD_AUTH}}
          image_name: 'action-test:${{ github.sha }}'
          registry: 'gcr.io'
          cluster: ${{ secrets.CLUSTER}}
          zone: ${{ secrets.ZONE}}
          deployment: ${{ secrets.DEPLOYMENT}}
          namespace: ${{ secrets.NAMESPACE}}
          container: ${{ secrets.CONTAINER}}
          project_id: ${{ secrets.PROJECT_ID}}
